### ISSUE TITLE
no integration in ha after install

### ISSUE THREAD

**Issue by dreamer2** [v1ack/lelight#1]
i see in log message about integration
"2022-08-29 10:35:42.459 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lelight which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant"

but not on integrations list

**Comment by v1ack** [comment]
The warning is standard for any custom integration, don't worry.
If you added custom component and steel can't see new integration - restart home assistant and reload home assistant webpage without cache (more https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/)

Then you will be able to find it in adding integration menu under name `LeLight (IRALAN)`

**Comment by dreamer2** [comment]
noted log entry to skip file downloading/unpacking problems discussion

clearing browser cache/reboot host/ha relog  not help
```

Home Assistant 2022.8.7 
Supervisor 2022.08.3 
Operating System 8.5 
Frontend 20220802.0 - latest 
```

**Comment by v1ack** [comment]
Is there any other logs related to integration?

**Comment by dreamer2** [comment]
any additional log for custom integrations?
because in home assistant core log only warning like above

**Comment by v1ack** [comment]
I've just tested installing integration in new Home Assistant container.
After integration installation and HA reboot - no changes.
But when I reloaded the page without cache (in safari with turning off cache in dev tools -> network panel) it appears
<img width="1069" alt="Снимок экрана 2022-08-29 в 23 15 32" src="https://user-images.githubusercontent.com/11501957/187290086-801a85fb-569d-4517-baca-812946c7395b.png">

**Comment by dreamer2** [comment]
ok, after some ha restarts i see it
will try codes and using later

**Comment by xrays72** [comment]
Привет, подскажите, пожалуйста, этому компоненту нужен докер контейнер, который ранее был нужен для https://github.com/v1ack/smartLightConnector?

**Comment by dreamer2** [comment]
В настройках компонента нет ничего кроме id устройства, так что предполагаю что не нужен.

**Comment by xrays72** [comment]
> В настройках компонента нет ничего кроме id устройства, так что предполагаю что не нужен.

супер, а то я в попытке поднять контейнер в docker-compose и доустановки нужных обновлений убил свой hassio.
сейчас развернул с нуля, компонент ble monitor работает, возможно и этот заработает если ему контейнер не нужен.

**Comment by v1ack** [comment]
Интеграции ничего не требуется, кроме наличия Bluetooth на устройстве.
Устанавливать уже можно через hacs

**Comment by xrays72** [comment]
> Интеграции ничего не требуется, кроме наличия Bluetooth на устройстве. Устанавливать уже можно через hacs

Шикарно.
Пока не понял как в GM Smart Light сделать привязку к люстре.
У меня есть приложение [SmartControl](https://new.zscbled.com/app/download), к которому люстра привязана, но current id в ней не нашёл.

На [4pda ](https://4pda.to/forum/index.php?showtopic=1032028) нашёл следующий метод подключения приложения GM Smart Light к устройству:
1. Включите bluetooth на мобильном телефоне (необходимо включить только bluetooth, подключаться НЕ нужно).
2. Сначала выключите свет с обычного выключателя, НЕ пульта.
3. Включите свет (выключатель) и тут же нажмите на кнопку на телефоне и держите её в течение 5 секунд.
4. Свет на лампе будет мигать непрерывно (или 3-4 раза), чтобы показать успешное соединение.

Подскажите, пожалуйста, этот метод рабочий или нужно по другому делать?

Кстати есть ещё статья на [sprut](https://sprut.ai/article/integraciya-svetodiodnoy-lyustry-s-pultom-v-home-assistant), но там прям харкор какой-то с пайкой провод к пульту.

**Comment by v1ack** [comment]
Да, алгоритм подключения верный.
Судя по тому что у вас приложение вообще с другого сайта (те три что в описании интеграции я нашел на lelight.cn), возможно в вашей люстре другой контроллер.
Свою люстру к SmartControl я тоже подключить не смог.

Как будет время - попробую разобрать ваше приложение, предполагаю что алгоритм работы должен быть +- такой же.

Вообще у этих люстр зоопарк с приложениями

**Comment by xrays72** [comment]
> Да, алгоритм подключения верный. Судя по тому что у вас приложение вообще с другого сайта (те три что в описании интеграции я нашел на lelight.cn), возможно в вашей люстре другой контроллер. Свою люстру к SmartControl я тоже подключить не смог.
> 
> Как будет время - попробую разобрать ваше приложение, предполагаю что алгоритм работы должен быть +- такой же.
> 
> Вообще у этих люстр зоопарк с приложениями

Постараюсь сегодня сделать привязку по алгоритму к GM Smart Light, в крайнем случае в ближайшие 2 дня. 
Надеюсь привяжется т.к. led драйвер от iralan и тогда вам не придется тратить время на SmartControl :)

**Comment by dreamer2** [comment]
у меня тоже другие приложения, вечером буду пробовать эти.
и может эту закроем

**Comment by v1ack** [comment]
Попробуй ещё приложение https://play.google.com/store/apps/details?id=com.jingyuan.lamp 
Я посмотрел, разобрать приложения smart control и pc lamper почти нереально, а с LampSmart может вполне получиться.
И там точно другой алгоритм, не как в моей интеграции, но смысл тот же

**Comment by dreamer2** [comment]
у меня с ним не получается, вообще сейчас только smart control зацепился, даже pclamper не спаривается, не помню работал раньше или нет

**Comment by xrays72** [comment]
Перебрал разные приложения.

LampSmart  при подключении люстры гасит её и люстра обратно включается, но реакция на кнопки в приложении не происходит, будто люстра другие команды ждёт.
Так же себя ведёт Smart Light 1.1.6.

Визуально на SmartControl похоже приложение FanLamp 3.4.3, но оно к люстре не подключается.

**Comment by xrays72** [comment]
> у меня с ним не получается, вообще сейчас только smart control зацепился, даже pclamper не спаривается, не помню работал раньше или нет

pc lamper у меня без проблем к люстре подключился.
qr code у него какой-то свой и не совместим со smart control
<details>
  <summary>скрин qrcode + id</summary>
<img src="https://user-images.githubusercontent.com/2736976/187727165-f99478d8-5f37-43f7-9271-f63d8f4cb8e9.jpg">
</details>

**Comment by Di1Ly** [comment]
есть ли продвижения с адаптацией интеграции для контроллеров типа LampSmart Pro ?
У таких контроллеров другой алгоритм привязки приложения. Для этого есть отдельная кнопка, если ее нажать, контроллер переходит в режим привязки, после чего происходит процесс обмена пакетами.
Хотя пульт управления привязывается нажатием кнопки ON и работает как с контроллерами типа GM Smart Light,  так и с типа LampSmart Pro. Значит команды проходят стандартно, как минимум для пульта.

**Comment by caideone** [comment]
> 你可以把它放在一边，然后把它放在一边。и может эту закроем

大佬 你现在可以在 homeassistant 控制灯吗

**Comment by dreamer2** [comment]
sad but lamps with SmartControl app don't work with this integration

**Comment by caideone** [comment]
> 遗憾的是带有 SmartControl 应用程序的灯不能与此集成一起使用

可以试试这个，https://github.com/aronsky/esphome-components
你有联系方式吗 我有lelight的gateway

**Comment by dreamer2** [comment]
sorry i cannot check lamp at this time

**Comment by caideone** [comment]
我成功安装了集成，但是在控制时灯没有反应。 @v1ack 
![微信图片_20231127200858](https://github.com/v1ack/lelight/assets/61871842/9a85c238-6b19-410c-b18f-56333e39d807)
