### ISSUE TITLE
Not work in Orange Pi4 LTS

### ISSUE THREAD

**Issue by cRazyK67** [v1ack/lelight#3]
I have Iralan chandelier and control her via gm smart app.
Installed and configured LeLight HA Integration.

Control chandelier via HA not have effect.

![Screenshot_20230120_085157](https://user-images.githubusercontent.com/109964947/213627419-e03929e2-13f7-43b3-a2bf-8e5253019f44.jpg)
![Screenshot_20230120_085452_io homeassistant companion android](https://user-images.githubusercontent.com/109964947/213627423-e037cc7e-eb38-4404-aae0-d49596803675.jpg)
![Screenshot_20230120_085126_io homeassistant companion android](https://user-images.githubusercontent.com/109964947/213627427-51bdb829-b74d-4f43-b174-7dbd8fdd12bc.jpg)
![Screenshot_20230120_085043_com gm simpleble](https://user-images.githubusercontent.com/109964947/213627428-67d87647-ec70-40ac-ae9a-7b31d0b2d3c1.jpg)

**Comment by v1ack** [comment]
Попробуй новую версию, там увеличенная сила сигнала. 
Если всё равно не будет работать, то можно вручную подкрутить в файле `custom_components/lelight/connector_bless.py:21`
```python
self.adv._tx_power = 35
```
Чем больше число - тем сильнее сигнал. Но границы значений я не знаю, ставил наугад

**Comment by cRazyK67** [comment]
Попробовал.
Последние пару дней "игрался" с параметром tx_power, гуглил какой он может быть для моего чипсета... но все безрезультатно...
Грешил на работу Bluetooth на моей сборке хомяка, но там все работает, т.к. трекеры iBeacon он обнаруживает.

В терминале я вижу, что из хомяка в шину DBus сообщения отправляются.
[lelight.log](https://github.com/v1ack/lelight/files/10948369/lelight.log)

Однако не знаю правильно ли формируется пакет...
Хотел перехватить трекером пакеты на телефоне из приложения GM smart light (вдруг их формат как-то зависит от DeviceID???)? но не получилось...
Пакеты с пульта тоже пока не удалось перехватить...

Может есть какие идеи, т.к. очень хочется управлять люстрой из хомяка?

**Comment by caideone** [comment]
> Попробовал。 Последние пару дней "игрался" с параметром tx_power, гуглил какой он может быть для моего чипсета... но все безрезультатно... Гр蓝牙是一种蓝牙技术，它可以与蓝牙连接 。iBeacon 是一个应用程序。
> 
> 与此相关的是，DBus 还支持 отправляются。 [乐莱特日志](https://github.com/v1ack/lelight/files/10948369/lelight.log)
> 
> Однако не знаю правильно ли формируется пакет... Хотел перехватить трекером пакеты на телефоне из приложения GM 智能灯 (вдруг) их формат как-то зависит от DeviceID???)？но не получилось... Пакеты с пульта тоже пока не удалось перехватить...
> 
> Может есть какие идеи, т.к。очень хочется управлять люстрой из хомяка？

Have you taken care of it

**Comment by caideone** [comment]
> 我有伊朗吊灯并通过通用智能应用程序控制她。 安装并配置LeLight HA集成。
> 
> 通过HA控制吊灯没有效果。
> 
> ![截图_20230120_085157](https://user-images.githubusercontent.com/109964947/213627419-e03929e2-13f7-43b3-a2bf-8e5253019f44.jpg) ![Screenshot_20230120_085452_io homeassistant 伴侣 android](https://user-images.githubusercontent.com/109964947/213627423-e037cc7e-eb38-4404-aae0-d49596803675.jpg) ![Screenshot_20230120_085126_io homeassistant 伴侣 android](https://user-images.githubusercontent.com/109964947/213627427-51bdb829-b74d-4f43-b174-7dbd8fdd12bc.jpg) ![Screenshot_20230120_085043_com gm simpleble](https://user-images.githubusercontent.com/109964947/213627428-67d87647-ec70-40ac-ae9a-7b31d0b2d3c1.jpg)

我的也是

**Comment by caideone** [comment]
> 我有伊朗吊灯并通过通用智能应用程序控制她。 安装并配置LeLight HA集成。
> 
> 通过HA控制吊灯没有效果。
> 
> ![截图_20230120_085157](https://user-images.githubusercontent.com/109964947/213627419-e03929e2-13f7-43b3-a2bf-8e5253019f44.jpg) ![Screenshot_20230120_085452_io homeassistant伙伴android](https://user-images.githubusercontent.com/109964947/213627423-e037cc7e-eb38-4404-aae0-d49596803675.jpg) ![Screenshot_20230120_085126_io homeassistant伙伴android](https://user-images.githubusercontent.com/109964947/213627427-51bdb829-b74d-4f43-b174-7dbd8fdd12bc.jpg) ![Screenshot_20230120_085043_com gm simpleble](https://user-images.githubusercontent.com/109964947/213627428-67d87647-ec70-40ac-ae9a-7b31d0b2d3c1.jpg)

大佬 你搞定没
